apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-rabbit-demo

resources:
  - resources/namespace.yaml

bases:
  - consumer

commonLabels:
  managed-by: kustomize
  part-of: go-rabbit-demo
