apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml

configMapGenerator:
  - name: go-rabbit-demo-env-vars
    behavior: create
    literals:
      - CONSUMER_ENV=
      - GO_OPTIONS=
