kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-rabbit-consumer
  labels:
    name: go-rabbit-consumer
    component: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        name: go-rabbit-consumer
        component: consumer
    spec:
      containers:
        - name: go-rabbit-consumer
          image: go-rabbit-consumer
          env:
            - name: RABBIT_URL
              value: "amqp://guest:guest@hello-world:5672/"
            - name: QUEUE_NAME
              value: "testQueue2"
            - name: ROUTING_KEY
              value: "bye"
            - name: EXCHANGE
              value: "exchange1"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: Never
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
