kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-rabbit-demo
  labels:
    name: go-rabbit-demo
    component: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        name: go-rabbit-demo
        component: consumer
    spec:
      containers:
        - name: go-rabbit-demo
          image: go-rabbit-demo
          env:
            - name: CONSUMER_ID
              value: "rabbit"
          envFrom:
            - configMapRef:
                name: go-rabbit-demo-env-vars
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: Always
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
